project_id = "veorhexddrwlwxtkuycb"

[functions.spotify-auth]
verify_jwt = false

[functions.spotify-search]
verify_jwt = false

[functions.generate-reflection]
verify_jwt = false

[functions.generate-reflection-demo]
verify_jwt = false

[functions.spotify-playback-token]
verify_jwt = false

